
name: CI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
        # https://github.com/actions/checkout
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v1

        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build

        - run: npm install
        - run: npm run build

        env:
          CI: true
      - name: Run linter

        run: npm run lint
      - name: Test & publish code coverage
        # https://github.com/paambaati/codeclimate-action
        uses: paambaati/codeclimate-action@v2.4.0
        # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run coverage
          debug: true